title: Amanpreet Singh
author: Amanpreet Singh
email: amanpreetsingh459@gmail.com
description: An Artificial Intelligence Wizard's Blog
twitter_username: amanpreet_hmh
github_username: amanpreetsingh459

#Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
theme: minima

#Build settings
kramdown:
input: GFM
hard_wrap: false
auto_ids: true
footnote_nr: 1
entity_output: as_char
toc_levels: 1..6
smart_quotes: lsquo,rsquo,ldquo,rdquo
enable_coderay: false
